# Generated by Django 3.2.9 on 2021-11-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyMost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CartMost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FavMost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_clss_id', models.CharField(max_length=20)),
                ('pv', models.IntegerField()),
                ('buy', models.IntegerField()),
                ('cart', models.IntegerField()),
                ('fav', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(max_length=20)),
                ('pv', models.IntegerField()),
                ('buy', models.IntegerField()),
                ('cart', models.IntegerField()),
                ('fav', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBehaviorTopN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=7)),
                ('pv', models.CharField(max_length=100)),
                ('buy', models.CharField(max_length=100)),
                ('cart', models.CharField(max_length=100)),
                ('fav', models.CharField(max_length=100)),
            ],
        ),
    ]
