# Generated by Django 3.0.7 on 2021-11-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehaviorTopN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=7)),
                ('pv', models.CharField(max_length=100)),
                ('buy', models.CharField(max_length=100)),
                ('cart', models.CharField(max_length=100)),
                ('fav', models.CharField(max_length=100)),
            ],
        ),
    ]
