# Generated by Django 3.2.9 on 2021-11-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_clss_id', models.CharField(max_length=20)),
                ('pv', models.CharField(max_length=100)),
                ('buy', models.CharField(max_length=100)),
                ('cart', models.CharField(max_length=100)),
                ('fav', models.CharField(max_length=100)),
            ],
        ),
    ]
